### ISSUE TITLE
Çalıştıramadım

### ISSUE THREAD

**Issue by derdofan01** [QwertyRcode/bos-qwertylib-altyapi#1]
`qwertyl.calistir();` Denedim Olmadı

**Comment by QwertyRcode** [comment]
`herşeyin altına in ve qwertyl(client, ayarlar)` yaz ayarlar kısmı senin kendi ayarların olacak ismi değiştire bilirsin clientda client yani :D

**Comment by derdofan01** [comment]
Sağolasın Çalıştı :)
